# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tucil-3-KriptoKoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from digitalsign import *
from RSA import *
from filereader import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(709, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 441, 81))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 130, 651, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.generate = QtWidgets.QWidget()
        self.generate.setObjectName("generate")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.generate)
        self.plainTextEdit.setGeometry(QtCore.QRect(235, 125, 301, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.generate)
        self.label_2.setGeometry(QtCore.QRect(75, 130, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.generate)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.generate)
        self.pushButton.setGeometry(QtCore.QRect(250, 220, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.generate, "")
        self.sign = QtWidgets.QWidget()
        self.sign.setEnabled(True)
        self.sign.setMouseTracking(True)
        self.sign.setAccessibleName("")
        self.sign.setAutoFillBackground(True)
        self.sign.setObjectName("sign")
        self.label_4 = QtWidgets.QLabel(self.sign)
        self.label_4.setGeometry(QtCore.QRect(240, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.sign)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 230, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.sign)
        self.label_5.setGeometry(QtCore.QRect(70, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.sign)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(170, 110, 301, 41))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_6 = QtWidgets.QLabel(self.sign)
        self.label_6.setGeometry(QtCore.QRect(70, 170, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.sign)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(170, 160, 301, 41))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.sign)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 120, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.sign)
        self.pushButton_5.setGeometry(QtCore.QRect(490, 170, 75, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.sign, "")
        self.validate = QtWidgets.QWidget()
        self.validate.setObjectName("validate")
        self.label_7 = QtWidgets.QLabel(self.validate)
        self.label_7.setGeometry(QtCore.QRect(70, 130, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.validate)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 260, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.validate)
        self.label_8.setGeometry(QtCore.QRect(70, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.validate)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(160, 120, 301, 41))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.validate)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(160, 70, 301, 41))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_9 = QtWidgets.QLabel(self.validate)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.validate)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 130, 75, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.validate)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 80, 75, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.validate)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(160, 180, 301, 41))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.label_10 = QtWidgets.QLabel(self.validate)
        self.label_10.setGeometry(QtCore.QRect(70, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.validate)
        self.pushButton_8.setGeometry(QtCore.QRect(480, 190, 75, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_11 = QtWidgets.QLabel(self.validate)
        self.label_11.setGeometry(QtCore.QRect(180, 220, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.validate, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.genkey)
        self.pushButton_2.clicked.connect(self.gensign)
        self.pushButton_3.clicked.connect(self.signverif)
        self.pushButton_4.clicked.connect(self.browsefile)
        self.pushButton_5.clicked.connect(self.browseprivate)
        self.pushButton_7.clicked.connect(self.browsefileverif)
        self.pushButton_6.clicked.connect(self.browsepubkey)
        self.pushButton_8.clicked.connect(self.browsesign)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Digital Signature</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nama File Output"))
        self.label_3.setText(_translate("MainWindow", "RSA Key Generate"))
        self.pushButton.setText(_translate("MainWindow", "GENERATE KEY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generate), _translate("MainWindow", "Generate Key"))
        self.label_4.setText(_translate("MainWindow", "File Digital Sign"))
        self.pushButton_2.setText(_translate("MainWindow", "SIGN FILE"))
        self.label_5.setText(_translate("MainWindow", "File Input"))
        self.label_6.setText(_translate("MainWindow", "Private Key"))
        self.pushButton_4.setText(_translate("MainWindow", "Browse"))
        self.pushButton_5.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sign), _translate("MainWindow", "Digital Sign"))
        self.label_7.setText(_translate("MainWindow", "File Key"))
        self.pushButton_3.setText(_translate("MainWindow", "CHECK FILE"))
        self.label_8.setText(_translate("MainWindow", "File Input"))
        self.label_9.setText(_translate("MainWindow", "Sign Verification"))
        self.pushButton_6.setText(_translate("MainWindow", "Browse"))
        self.pushButton_7.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "File Sign"))
        self.pushButton_8.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "*jika file input berupa .txt kosongkan file sign"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.validate), _translate("MainWindow", "Validate"))

    def clicker(self):
        fname = QFileDialog.getOpenFileName(
            parent = MainWindow, 
            caption = "Open File",
            directory = "", 
            filter = "All Files (*)")
        if fname:
            return fname[0]
    
    def genkey(self):
        filename = self.plainTextEdit.toPlainText()
        writeKey(filename)
        self.popupnotifbiasa("Kunci telah berhasil dibuat")

    def gensign(self):
        filename = self.plainTextEdit_2.toPlainText()
        privatekey = self.plainTextEdit_3.toPlainText()
        if filename == "" or privatekey == "":
            self.popupnotiferror("File dan private key tidak boleh kosong!")
        else:    
            if self.prikeychecker(privatekey)==True:
                generateDigitalSigned(filename, privatekey)
                self.popupnotifbiasa("File berhasil ditandatangani")
            else:
                self.popupnotiferror("Masukkan kunci private (dengan file .pri)!")

    def browsefile(self):
        link = self.clicker()
        self.plainTextEdit_2.setPlainText(link)    

    def browseprivate(self):
        link = self.clicker()
        self.plainTextEdit_3.setPlainText(link)    

    def browsefileverif(self):
        link = self.clicker()
        self.plainTextEdit_5.setPlainText(link)

    def browsepubkey(self):
        link = self.clicker()
        self.plainTextEdit_4.setPlainText(link)    

    def browsesign(self):
        link = self.clicker()
        self.plainTextEdit_6.setPlainText(link)    

    def signverif(self):
        filename = self.plainTextEdit_5.toPlainText()
        filekey = self.plainTextEdit_4.toPlainText()
        filesign = self.plainTextEdit_6.toPlainText()
        
        if filename=="" or filekey=="":
            self.popupnotiferror("File name dan file key tidak boleh kosong!")

        else:
            if filereader.fileext(filename) == ".txt":
                if filesign != "":
                    self.popupnotiferror("Kosongkan file sign! \n.txt tidak perlu filesign")
                else:
                    if self.pubkeychecker(filekey) == True:
                        hasil = validateDigitalSigned(filename, filekey, filesign)
                        if hasil == "Valid":
                            self.popupnotifbiasa("File asli dan berhasil diverifikasi")
                        elif hasil == "Tidak Valid":
                            self.popupnotifwarning("Verifikasi gagal! \n File asli sudah berubah atau Anda salah memasukkan kunci")
                    else:
                        self.popupnotiferror("Masukkan kunci publik (dengan file .pub)!")

            else:
                if filesign == "":
                    self.popupnotiferror("Masukkan file sign!")
                else:
                    if self.pubkeychecker(filekey) == True:
                        hasil = validateDigitalSigned(filename, filekey, filesign)
                        if hasil == "Valid":
                            self.popupnotifbiasa("File asli dan berhasil diverifikasi")
                        elif hasil == "Tidak Valid":
                            self.popupnotifwarning("Verifikasi gagal! \n File asli sudah berubah atau Anda salah memasukkan kunci")
                    else:
                        self.popupnotiferror("Masukkan kunci publik (dengan file .pub)!")

    def popupnotifbiasa(self, kalimat):
        msg = QMessageBox()
        msg.setWindowTitle("Digital Signature")
        msg.setText(kalimat)
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def popupnotifwarning(self, kalimat):
        msg = QMessageBox()
        msg.setWindowTitle("Digital Signature")
        msg.setText(kalimat)
        msg.setIcon(QMessageBox.Warning)

        x = msg.exec_()

    def popupnotiferror(self, kalimat):
        msg = QMessageBox()
        msg.setWindowTitle("Digital Signature")
        msg.setText(kalimat)
        msg.setIcon(QMessageBox.Critical)

        x = msg.exec_()    

    def pubkeychecker(self, file):
        if filereader.fileext(file) == ".pub":
            return True
        else:
            return False

    def prikeychecker(self, file):
        if filereader.fileext(file) == ".pri":
            return True
        else:
            return False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

    '''
QmessageBox.Ok
    '''
